name: Build LaTeX on tag

on:
  push:
    tags:
      - '*'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: xu-cheng/latex-action@v2
        with:
          root_file: card.tex

      - name: Upload compiled PDF
        uses: actions/upload-artifact@v4
        with:
          name: business-card
          path: card.pdf

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "Business Card Release ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload PDF to Release
        uses: softprops/action-gh-release@v1
        with:
          files: card.pdf
